### ISSUE TITLE
Reading Unicode characters in R 

### ISSUE THREAD

**Issue by bnafack** [B23579/Sueza_project#5]
I was trying to read the CSV file containing the following text: Akhu míá ŋgap, à gɔ te zwɛ mɔ ŋgapá. But I got the strange characters shown in the 
![isue1](https://user-images.githubusercontent.com/58120702/162086449-2949b3d9-1197-4ed4-ab81-ee4f0506af9c.jpg)
figure joins.

**Comment by bnafack** [comment]
I used the following python code 
lines = []
with open('Downloads/text.txt','r',encoding='utf8') as f:
    lines = f.readlines()
f.close()
count = 0
for line in lines:
    count += 1
    print(f'line {count}: {line}')    
    
it works, however without encoding='utf8', I got the same output when using R. Furthermore,  pd.read_csv() routine doesn't give a nice output.

**Comment by bnafack** [comment]
To solve the issue got with r, I used the library tm  with encoding = 'utf8'

I use the following syntax 

archive_test <- file.path ("project", "Sueza_project", "Data","Yemba","corpus")
archive_test
dir (archive_test)
corpus.source <- Corpus(DirSource(archive_test,encoding = "UTF-8"),readerControl = list(language = "lat"))

It works very well.

**Comment by tem-ctrl** [comment]
Happy to know you got this issu fixed by your own means.
